"""Stage-agnostic vNext workflow surfaces."""

from .construction import (
    CONSTRUCTION_PHASES,
    ConstructionMark,
    InitialConstruct,
    InitialConstructResult,
    PoseObservation,
    author_initial_construct,
    inspect_initial_construct,
    observe_pose,
)
from .correction import CorrectionRecord, ResidualRecord
from .evidence import EvidencePolicy, EvidenceReadRecord, EvidenceTelemetry
from .intent import (
    COMPATIBILITY_INTENTS,
    DRAWING_MODES,
    FINISH_INTENTS,
    FINISH_GUIDE_SCHEMA,
    FINISH_RELATION_SCHEMA,
    REFERENCE_MODES,
    STYLE_PROFILES,
    DrawingIntent,
    FinishGuide,
    FinishRelation,
    IntentChangeRecord,
    IntentProvenance,
    ModeGuide,
    StyleGuide,
    compatibility_intent,
    resolve_mode_guide,
    resolve_finish_guide,
    resolve_style_guide,
)
from .session import DrawingSession
from .value import replace_fill_region

__all__ = [
    "CONSTRUCTION_PHASES",
    "CorrectionRecord",
    "ConstructionMark",
    "DrawingSession",
    "EvidencePolicy",
    "EvidenceReadRecord",
    "EvidenceTelemetry",
    "COMPATIBILITY_INTENTS",
    "DRAWING_MODES",
    "FINISH_INTENTS",
    "FINISH_GUIDE_SCHEMA",
    "FINISH_RELATION_SCHEMA",
    "REFERENCE_MODES",
    "STYLE_PROFILES",
    "DrawingIntent",
    "FinishGuide",
    "FinishRelation",
    "IntentChangeRecord",
    "IntentProvenance",
    "ModeGuide",
    "StyleGuide",
    "compatibility_intent",
    "resolve_mode_guide",
    "resolve_finish_guide",
    "resolve_style_guide",
    "InitialConstruct",
    "InitialConstructResult",
    "PoseObservation",
    "ResidualRecord",
    "author_initial_construct",
    "inspect_initial_construct",
    "observe_pose",
    "replace_fill_region",
]
