from .model import StageSpec

FULL_BODY_CROQUIS = (
    StageSpec(
        "P1_gesture", 1, "Gesture / Construction Centrelines",
        "Build a whole-body pose hypothesis. P1 is not a few simple lines: head, spine, shoulder and pelvis rhythm, both arms, both legs, foot direction and any large prop must all be readable at minimum information.",
        (
            "crown position, and the curvature of the facial centreline through nose and chin",
            "head tilt from the eye-line cross",
            "the spine's S-curve, starting behind the neck",
            "pelvis centreline and its tilt",
            "shoulder line and its tilt",
            "the line of action, which is not the spine",
            "shoulder, elbow, wrist, hip, knee and ankle centres",
            "the curvature of each limb between those joints",
            "any limb hidden behind clothing or a prop",
            "where the feet meet the ground and which way each foot points",
            "the overall silhouette envelope",
            "the major axis of a large attached object",
        ),
        (
            "the head outline read from the subject, a facial centreline through crown → between the eyes → nose → mouth → chin, and an eye line through both eyes",
            "a separate spine centreline: an S-curve from behind the neck through mid-back, waist and sacrum",
            "pelvis and shoulder lines stating their tilt",
            "one line of action entering above the head, cutting across the body and landing ahead of the weight-bearing foot",
            "joint markers as small circles",
            "flowing limb lines that follow observed curvature, not straight joins",
            "an inferred flow line through an occluded limb, ending where the hidden hand or foot must be",
            "a loose flowing torso mass",
            "each foot's observed shape linked to its ankle, stating the direction it points",
            "ground contact marks under each foot",
            "the major axis of a large attached object",
        ),
        (
            "reading the hair silhouette as the cranial outline",
            "dropping a generic ellipse in for the head or a foot instead of observing its shape",
            "drawing the facial centreline as a plain vertical centre line",
            "running the facial centreline beside the nose instead of through it",
            "drawing the eye line without checking it meets both eyes",
            "merging the face and spine centrelines into one stroke",
            "joining joints with straight lines",
            "dropping an occluded limb because it cannot be seen",
            "copying joint positions from an example drawing instead of the subject",
            "moving a line to satisfy a filter or evidence map",
            "footwear detail — state the foot's direction and shape, not its laces and panels",
            "facial features, hair, garment structure, muscle or closed volume",
        ),
        review_questions=(
            "Overlay P1 on the subject: does the crown sit where the subject's crown sits, and is the head outline the subject's shape rather than a generic ellipse?",
            "Does the eye line say what the subject's head tilt says — level, up, or down — rather than whatever the ellipse happened to give?",
            "Does the facial centreline actually pass through the nose? A centreline beside the nose turns the face the wrong way, however good the outline is.",
            "Does the eye line pass through both eyes, and does its tilt come from where those two eyes sit rather than from a guess?",
            "Is the spine an S-curve that starts behind the neck, not at the chin, and is it a separate stroke from the facial centreline?",
            "Do shoulder and pelvis state the subject's rotation, not just a tilt?",
            "Are both arms present, including any hidden behind a prop or in a pocket?",
            "Is every joint centre on the subject's joint, or are several drifting the same way?",
            "Does each limb follow the subject's observed curvature, or was it joined straight?",
            "Do the feet land where the subject's land, and does each foot oval point the way that foot points?",
            "Do the foot directions agree with the body direction the rest of the drawing states?",
            "Is any part merely 'roughly around here'?",
            "With the subject hidden, does this read as this specific person in this specific pose — not just as a person?",
        ),
        advance_when=(
            "Overlaid on the subject, head direction, spine curvature, shoulder and pelvis rotation, both arms, both legs' joint centres and both foot directions all register.",
            "No part of the drawing is 'roughly around here'.",
            "With the subject hidden, the drawing reads as this specific person in this specific pose.",
            "Any occluded limb has a stated hypothesis rather than being absent.",
            "No joint drift, no straight landmark joins, no merged face/spine stroke.",
        ),
        suggested_crops=("crown+face centreline", "neck+upper spine", "shoulder rhythm", "pelvis+hips", "each arm including occluded ones", "each leg", "ankles, foot direction and ground contact"),
    ),
    StageSpec(
        "P2_primary_axes", 2, "Primary Axes",
        "Turn P1's flow into measured structure: segment lengths, foreshortening and the ribcage/pelvis volumes the mannequin needs. P1 said where the joints are; P2 says how long each bone is and how it is turned.",
        (
            "the length of each limb segment against the subject",
            "foreshortening of each segment",
            "neck axis",
            "ribcage centre axis and how the ribcage box is turned",
            "pelvis axis and how the pelvis box is turned",
            "where the hands and feet sit as blocks",
            "any P1 joint that the measured chain proves was misplaced",
            "attached-object length and tilt relative to the body",
        ),
        (
            "limb segments as measured straight or lightly cylindrical axes",
            "ribcage and pelvis axis volumes",
            "the hip → knee → ankle → foot chain as connected segments",
            "the shoulder → elbow → wrist → hand chain as connected segments",
            "simple hand and foot placement blocks",
            "corrected joint positions where the measured chain disagrees with P1",
            "the attached object as a measuring axis against the body",
        ),
        (
            "facial features",
            "hair",
            "clothing",
            "finished limb contour",
            "surface or garment detail",
        ),
        review_questions=(
            "Are the P1 centrelines — face, spine, pelvis — and the line of action still readable underneath?",
            "Does each segment's length match the subject, or was it drawn to a comfortable proportion?",
            "Does each segment read the subject's foreshortening? A limb coming toward the viewer is short.",
            "Are the ribcage and pelvis boxes turned the way the subject's are?",
            "Do the hand and foot blocks sit where the subject's hands and feet sit, including any in a pocket?",
            "If a joint moved from P1, was that because the subject says so — or to make the drawing easier?",
            "Is the attached object's length and tilt measured against the body rather than guessed?",
            "Did the worker stop before finished contour, clothing and hair?",
        ),
        advance_when=(
            "Segment lengths and foreshortening agree with the subject.",
            "Ribcage and pelvis turn the way the subject's do.",
            "Hand and foot blocks are placed, including occluded ones.",
            "The P1 pose hypothesis survives; any joint correction is subject-driven.",
            "No major visible P2 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("neck+ribcage", "ribcage+pelvis boxes", "shoulder→elbow→wrist", "hip→knee→ankle", "hand blocks", "attached object against the torso"),
    ),
    StageSpec(
        "P3_primary_masses", 3, "Primary Masses",
        "Turn the stick figure into a body with volume: wrap simple three-dimensional masses around the P2 axes.",
        (
            "how thick the torso is",
            "ribcage and pelvis rotation",
            "limb thickness and taper",
            "which parts are in front of which",
            "overlap",
            "perspective",
            "whole-figure proportion",
            "the volume a large attached object occupies",
        ),
        (
            "simple three-dimensional volumes around head, ribcage, pelvis, shoulders, upper arms, forearms, thighs, calves, hands and feet",
            "cross-contours that state which way a volume points",
            "limb taper",
            "torso thickness and ribcage/pelvis rotation",
            "overlap and perspective cues",
            "a few garment or gear marks where they materially change the occupied volume",
        ),
        (
            "facial features",
            "individual hair strands",
            "clothing folds and seams",
            "finished garment silhouette",
            "hand and foot detail",
        ),
        review_questions=(
            "Does each limb read as a volume pointing somewhere, not two parallel outlines?",
            "Do the ribcage and pelvis show their rotation?",
            "Is the torso thickness credible against the subject?",
            "Are front/back and overlap relationships explicit?",
            "Does whole-figure proportion hold up at mass level?",
            "Are the P2 joint positions and directions preserved underneath?",
            "Did the worker keep garment detail and face out, adding only marks that change the occupied volume?",
        ),
        advance_when=(
            "The figure reads as a body with volume rather than a stick figure.",
            "Ribcage and pelvis rotation match the subject.",
            "Limb thickness, taper and overlap match the subject.",
            "Whole-figure proportion holds at mass level.",
            "No major visible P3 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head+ribcage", "ribcage+pelvis", "one full arm", "one full leg", "attached object volume"),
    ),
    StageSpec(
        "P4_structural_connections", 4, "Structural Connections",
        "Connect the real subject's form to the body masses: how clothing, hair and equipment sit on the volumes underneath. Structure, not decoration.",
        (
            "how the hair mass sits on the skull",
            "how the garment hangs across shoulder → sleeve → elbow → wrist",
            "waistline and garment openings",
            "hand and foot form",
            "footwear structure",
            "the major structure of a large attached object",
            "where straps, slings, holsters and pockets attach and overlap",
        ),
        (
            "hair as a large mass over the cranium",
            "garment structure resolved over the underlying volume",
            "hand and foot form and footwear structure",
            "major prop structure: barrel direction, stock, receiver, magazine, sling",
            "contact and overlap points between object and body",
            "minimal placement of facial features",
        ),
        (
            "buttons, stitching and micro garment detail",
            "individual hair strands",
            "micro folds",
            "surface texture",
            "tonal rendering",
        ),
        review_questions=(
            "Does the hair sit on the cranium as a mass, or was it drawn strand by strand?",
            "Does the garment hang on the arm chain rather than float beside it?",
            "Is the waistline placed on the pelvis volume from P3?",
            "Do the hands and feet grow out of their limbs instead of reading as detached blocks?",
            "Is the attached object's major structure connected to where it touches the body?",
            "Was structure solved before decoration — no buttons or stitching yet?",
            "Are the P3 volumes and proportion preserved underneath?",
        ),
        advance_when=(
            "The drawing reads as this specific subject, not a generic mannequin.",
            "Clothing, hair and equipment are connected to the volumes beneath them.",
            "Hands, feet and footwear have form and stay attached to their limbs.",
            "The attached object's major structure and body contact are explicit.",
            "No major visible P4 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head+hair", "shoulder→sleeve→wrist", "waist+garment opening", "hand", "foot+footwear", "object↔body contact"),
    ),
    StageSpec(
        "P5_clean_blockin", 5, "Clean Block-in",
        "Decide which lines are the final form. Clean means selection, not heavier strokes, and this is an under-drawing, not a finished illustration.",
        (
            "which explored line is the real contour",
            "the face form",
            "the hair silhouette",
            "the garment contour",
            "hands and footwear",
            "equipment form",
            "where overlapping lines need a break rather than a weld",
        ),
        (
            "the decided contour drawn first",
            "superseded construction subordinated with soft_lift rather than erased from history",
            "resolved face and hair silhouette",
            "major internal contour breaks",
            "an explicit occlusion handoff where one mass passes behind another",
        ),
        (
            "tonal shading and filled black areas",
            "surface texture",
            "excessive garment folds",
            "fine skin rendering",
            "welding two independent masses into one continuous contour",
            "beautification that changes verified structure",
        ),
        review_questions=(
            "Was the final line selected, or were the existing lines merely darkened?",
            "Is the face form clear without becoming rendered detail?",
            "Is the hair a resolved silhouette rather than strands?",
            "Are the garment contours decided?",
            "Are hands, footwear and equipment tidy?",
            "Where two masses overlap, does the contour hand off with a visible break instead of welding?",
            "Is this an under-drawing solid enough that detail would not collapse it?",
            "Did the worker avoid shading, texture and micro folds?",
        ),
        advance_when=(
            "The silhouette is readable and the surviving internal lines are chosen, not accumulated.",
            "Face, hair, garment, hands, footwear and equipment forms are decided.",
            "Contour ownership is explicit wherever masses overlap.",
            "The verified P1–P4 structure was not changed for the sake of a prettier line.",
            "No major visible P5 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head+face", "hair silhouette", "garment contour", "hands", "footwear", "overlap handoff regions"),
    ),
)
