from .model import StageSpec

FULL_BODY_CROQUIS = (
    StageSpec(
        "P1_gesture", 1, "Gesture / Weight Path",
        "Settle how the figure stands: flow, balance and centre of gravity. Do not try to draw the body accurately yet.",
        (
            "head position and tilt",
            "line of action through the whole body",
            "shoulder tilt",
            "pelvis tilt",
            "arm and leg direction",
            "where the feet meet the ground",
            "overall silhouette width and height",
            "major attached-object direction when it changes the envelope",
        ),
        (
            "a simple head ovoid with a light centre/tilt indication",
            "one dominant line of action",
            "shoulder line and pelvis line as tilt cues",
            "single-line arm and leg direction paths",
            "ground contact marks under the feet",
            "a loose envelope for the whole silhouette",
            "the major axis of a large attached object when relevant",
        ),
        (
            "facial features",
            "hair",
            "clothing",
            "muscle definition",
            "attached-object detail",
            "final contour",
        ),
        review_questions=(
            "Can a viewer tell which way this person is standing and where the weight sits?",
            "Is there one dominant line of action rather than several competing sticks?",
            "Do the shoulder and pelvis tilts match the subject?",
            "Do the arm and leg direction paths match the subject's real directions?",
            "Do the feet land where the subject's feet land?",
            "Are the overall silhouette width and height credible against the subject?",
            "Are head width/height, shoulder span and pelvis breadth derived from the subject rather than from a remembered generic figure?",
            "Did the worker keep clothing, hair, face and prop detail out?",
        ),
        advance_when=(
            "How the subject stands and where the weight sits is unambiguous.",
            "Shoulder and pelvis tilt agree with the subject.",
            "Limb directions and foot contact agree with the subject.",
            "The overall proportion envelope is credible at P1 abstraction.",
            "No major visible P1 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head+shoulders", "torso+pelvis", "pelvis+both legs", "feet and ground contact"),
    ),
    StageSpec(
        "P2_primary_axes", 2, "Primary Axes",
        "Take the pose apart into joints and axes: state where the bones are and which way each segment runs.",
        (
            "shoulder, elbow and wrist positions",
            "hip, knee and ankle positions",
            "head centreline and face direction",
            "neck axis",
            "ribcage centre axis",
            "pelvis axis",
            "upper-arm and forearm direction",
            "thigh and shin direction",
            "attached-object length and tilt relative to the body",
        ),
        (
            "joint markers as small circles",
            "limb segments as straight or lightly cylindrical axes",
            "the hip → knee → ankle → foot chain explicitly",
            "the shoulder → elbow → wrist → hand chain explicitly",
            "head centreline and facial direction cross",
            "simple hand and foot placement blocks",
            "the attached object as a measuring axis against the body",
        ),
        (
            "facial features",
            "hair",
            "clothing",
            "finished limb contour",
            "surface or garment detail",
        ),
        review_questions=(
            "Is the P1 line of action still readable underneath?",
            "Are the shoulder/elbow/wrist positions where the subject's are?",
            "Are the hip/knee/ankle positions where the subject's are?",
            "Is the hip → knee → ankle → foot chain explicit rather than one continuous leg curve?",
            "Does the head centreline state the same face direction as the subject?",
            "Do segment lengths read the subject's foreshortening?",
            "Is the attached object's length and tilt measured against the body rather than guessed?",
            "Did the worker stop before finished contour, clothing and hair?",
        ),
        advance_when=(
            "Every major joint has a position that agrees with the subject.",
            "Each limb segment states a direction rather than a finished shape.",
            "Head centreline and face direction agree with the subject.",
            "The P1 pose survives unchanged underneath the axes.",
            "No major visible P2 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head+neck", "shoulder→elbow→wrist", "hip→knee→ankle", "attached object against the torso"),
    ),
    StageSpec(
        "P3_primary_masses", 3, "Primary Masses",
        "Turn the stick figure into a body with volume: wrap simple three-dimensional masses around the P2 axes.",
        (
            "how thick the torso is",
            "ribcage and pelvis rotation",
            "limb thickness and taper",
            "which parts are in front of which",
            "overlap",
            "perspective",
            "whole-figure proportion",
            "the volume a large attached object occupies",
        ),
        (
            "simple three-dimensional volumes around head, ribcage, pelvis, shoulders, upper arms, forearms, thighs, calves, hands and feet",
            "cross-contours that state which way a volume points",
            "limb taper",
            "torso thickness and ribcage/pelvis rotation",
            "overlap and perspective cues",
            "a few garment or gear marks where they materially change the occupied volume",
        ),
        (
            "facial features",
            "individual hair strands",
            "clothing folds and seams",
            "finished garment silhouette",
            "hand and foot detail",
        ),
        review_questions=(
            "Does each limb read as a volume pointing somewhere, not two parallel outlines?",
            "Do the ribcage and pelvis show their rotation?",
            "Is the torso thickness credible against the subject?",
            "Are front/back and overlap relationships explicit?",
            "Does whole-figure proportion hold up at mass level?",
            "Are the P2 joint positions and directions preserved underneath?",
            "Did the worker keep garment detail and face out, adding only marks that change the occupied volume?",
        ),
        advance_when=(
            "The figure reads as a body with volume rather than a stick figure.",
            "Ribcage and pelvis rotation match the subject.",
            "Limb thickness, taper and overlap match the subject.",
            "Whole-figure proportion holds at mass level.",
            "No major visible P3 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head+ribcage", "ribcage+pelvis", "one full arm", "one full leg", "attached object volume"),
    ),
    StageSpec(
        "P4_structural_connections", 4, "Structural Connections",
        "Connect the real subject's form to the body masses: how clothing, hair and equipment sit on the volumes underneath. Structure, not decoration.",
        (
            "how the hair mass sits on the skull",
            "how the garment hangs across shoulder → sleeve → elbow → wrist",
            "waistline and garment openings",
            "hand and foot form",
            "footwear structure",
            "the major structure of a large attached object",
            "where straps, slings, holsters and pockets attach and overlap",
        ),
        (
            "hair as a large mass over the cranium",
            "garment structure resolved over the underlying volume",
            "hand and foot form and footwear structure",
            "major prop structure: barrel direction, stock, receiver, magazine, sling",
            "contact and overlap points between object and body",
            "minimal placement of facial features",
        ),
        (
            "buttons, stitching and micro garment detail",
            "individual hair strands",
            "micro folds",
            "surface texture",
            "tonal rendering",
        ),
        review_questions=(
            "Does the hair sit on the cranium as a mass, or was it drawn strand by strand?",
            "Does the garment hang on the arm chain rather than float beside it?",
            "Is the waistline placed on the pelvis volume from P3?",
            "Do the hands and feet grow out of their limbs instead of reading as detached blocks?",
            "Is the attached object's major structure connected to where it touches the body?",
            "Was structure solved before decoration — no buttons or stitching yet?",
            "Are the P3 volumes and proportion preserved underneath?",
        ),
        advance_when=(
            "The drawing reads as this specific subject, not a generic mannequin.",
            "Clothing, hair and equipment are connected to the volumes beneath them.",
            "Hands, feet and footwear have form and stay attached to their limbs.",
            "The attached object's major structure and body contact are explicit.",
            "No major visible P4 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head+hair", "shoulder→sleeve→wrist", "waist+garment opening", "hand", "foot+footwear", "object↔body contact"),
    ),
    StageSpec(
        "P5_clean_blockin", 5, "Clean Block-in",
        "Decide which lines are the final form. Clean means selection, not heavier strokes, and this is an under-drawing, not a finished illustration.",
        (
            "which explored line is the real contour",
            "the face form",
            "the hair silhouette",
            "the garment contour",
            "hands and footwear",
            "equipment form",
            "where overlapping lines need a break rather than a weld",
        ),
        (
            "the decided contour drawn first",
            "superseded construction subordinated with soft_lift rather than erased from history",
            "resolved face and hair silhouette",
            "major internal contour breaks",
            "an explicit occlusion handoff where one mass passes behind another",
        ),
        (
            "tonal shading and filled black areas",
            "surface texture",
            "excessive garment folds",
            "fine skin rendering",
            "welding two independent masses into one continuous contour",
            "beautification that changes verified structure",
        ),
        review_questions=(
            "Was the final line selected, or were the existing lines merely darkened?",
            "Is the face form clear without becoming rendered detail?",
            "Is the hair a resolved silhouette rather than strands?",
            "Are the garment contours decided?",
            "Are hands, footwear and equipment tidy?",
            "Where two masses overlap, does the contour hand off with a visible break instead of welding?",
            "Is this an under-drawing solid enough that detail would not collapse it?",
            "Did the worker avoid shading, texture and micro folds?",
        ),
        advance_when=(
            "The silhouette is readable and the surviving internal lines are chosen, not accumulated.",
            "Face, hair, garment, hands, footwear and equipment forms are decided.",
            "Contour ownership is explicit wherever masses overlap.",
            "The verified P1–P4 structure was not changed for the sake of a prettier line.",
            "No major visible P5 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head+face", "hair silhouette", "garment contour", "hands", "footwear", "overlap handoff regions"),
    ),
)
