from .model import StageSpec

FULL_BODY_CROQUIS = (
    StageSpec(
        "P1_gesture", 1, "Gesture / Weight Path",
        "Capture the full craniofacial-to-ground gesture: face direction, spinal rhythm, pelvis transfer, support leg and counterbalance before anatomy.",
        (
            "crown and top of cranium",
            "curved facial centre line and unequal left/right head halves",
            "chin-to-neck exit",
            "neck-to-spine flow",
            "pelvis centre and tilt",
            "support-side hip and weight-bearing leg",
            "counterbalance leg",
            "shoulder rhythm",
            "major attached-object axis when it changes the global envelope",
        ),
        (
            "one dominant continuous stroke from crown through curved facial centre, chin, neck, spine, pelvis and support leg to the weight landing point",
            "open cranial/jaw envelope arcs; use a separate short crown arc when needed so the head does not collapse into one closed egg",
            "subordinate shoulder rhythm",
            "subordinate pelvis rhythm",
            "secondary counterbalance-leg flow",
            "restrained attached-object major axis when relevant",
            "minimal ground/weight cue only if needed",
        ),
        (
            "starting the main gesture at the neck instead of the crown",
            "straight geometric face centre that carries no face-direction information",
            "closed polygon/circle head symbol that overwhelms the face-axis relationship",
            "independent torso and leg sticks that break the neck→spine→pelvis→support path",
            "joint anatomy",
            "clothing detail",
            "final contour",
            "facial features",
        ),
        review_questions=(
            "Does the dominant gesture start at the crown, not at the neck?",
            "Inside the head, does the centre line curve asymmetrically and do the open crown/temporal/jaw arcs avoid reconstructing a closed badge?",
            "Does that same dominant intention continue through chin→neck→spine→pelvis→support leg without a conceptual break?",
            "Does the pelvis visibly transfer weight into one support leg instead of feeding two equivalent sticks?",
            "Does the opposite leg read as counterbalance?",
            "Are head width/height, shoulder span and pelvis breadth derived from the subject rather than from a remembered generic figure?",
            "Is the dominant gesture materially/visually stronger than secondary construction?",
            "Did the worker avoid P2/P3 anatomy, clothing and contour detail?",
            "If a large attached object changes balance or silhouette, is its major axis already present but subordinate?",
        ),
        advance_when=(
            "A viewer can infer the subject's head/face direction from the curved craniofacial centre line and head-envelope relationship.",
            "The full dominant weight path is readable from crown to the support landing point.",
            "Support and counterbalance roles are unambiguous.",
            "Large subject proportions (head/shoulder/pelvis/leg spread) are credible at P1 abstraction.",
            "Secondary construction supports the dominant gesture instead of competing with it.",
            "No major visible P1 mismatch remains after whole-view and relevant crop review.",
        ),
        suggested_crops=("head/face", "torso+pelvis", "pelvis+both legs", "attached object + shoulder when present"),
    ),
    StageSpec(
        "P2_primary_axes", 2, "Primary Axes",
        "Translate the closed P1 gesture into directional axes without losing its energy or support relationship.",
        ("head direction","shoulder tilt","pelvis tilt","limb directions","prop direction and breadth","foreshortening cues"),
        ("head axis","shoulder axis","pelvis axis","major limb axes","attached-object extent"),
        ("surface detail","folds","final contour","small anatomy","redrawing P1 as a new unrelated scaffold"),
        review_questions=(
            "Do head/shoulder/pelvis axes explain the same pose already established in P1?",
            "Do shoulder and pelvis tilts communicate twist rather than behave as unrelated bars?",
            "Do limb axes originate from the correct body masses rather than float independently?",
            "Does the attached-object breadth/axis agree with the subject and with the P1 global envelope?",
        ),
        advance_when=(
            "Axes clarify the P1 pose without changing its dominant gesture.",
            "Torso twist, pelvis relation, support leg and limb directions are readable.",
            "No major axis-level mismatch remains in subject-vs-drawing review.",
        ),
        suggested_crops=("head+shoulders", "torso+pelvis", "pelvis+legs", "prop overlap"),
    ),
    StageSpec(
        "P3_primary_masses", 3, "Primary Masses",
        "Turn verified axes into connected organic masses while preserving the P1/P2 rhythm.",
        ("ribcage volume","pelvis wedge","torso bridge","limb taper","overlap","head/hair mass","attached-object mass"),
        ("head mass","ribcage mass","pelvis mass","torso bridge","tapered limb masses","attached-object mass"),
        ("joint dots as substitutes for structure","box assembly that breaks spinal flow","clothing folds","rendered facial features"),
        review_questions=(
            "Do ribcage and pelvis read as connected organic masses rather than boxes?",
            "Does the torso bridge preserve spinal rhythm and twist?",
            "Do limbs taper and emerge from the pelvis/shoulder masses naturally?",
            "Does the attached object read as an integrated long mass rather than a floating object?",
        ),
        advance_when=(
            "The figure is readable as connected masses at a glance.",
            "The subject silhouette and major negative spaces are credible at mass level.",
            "No major mass/connection mismatch remains.",
        ),
        suggested_crops=("torso+pelvis", "shoulder+arm", "pelvis+thighs", "prop overlap"),
    ),
    StageSpec(
        "P4_structural_connections", 4, "Structural Connections",
        "Clarify functional joint transitions and how masses connect through the limb chains.",
        ("shoulder insertion","elbow turn","wrist direction","hip-to-thigh","knee plane","ankle-to-foot","prop overlap and attachment"),
        ("limb chains","partial directional joint planes","joint transitions","hands/feet blocks","overlap corrections","attachment relationships"),
        ("joint dots without form transition","full-width elbow/knee bands that read as clothing stripes","faceted detached hand/foot polygons","final shading","texture","decorative detail"),
        review_questions=(
            "Can each arm be followed shoulder→elbow→wrist as a connected chain?",
            "Can each leg be followed pelvis→knee→ankle as a connected chain?",
            "Do joints explain directional change with local transitions rather than dots or full-width decorative bands?",
            "If loose clothing hides a joint, is the functional transition readable without drawing a naked joint or a decorative full-width stripe?",
            "Do simple hand blocks attach to the wrist and respect occlusion instead of floating beside the sleeve?",
            "Are feet/boots smoothly connected to the ankle, directionally credible and grounded?",
            "Are holsters/straps/props physically attached rather than floating?",
        ),
        advance_when=(
            "Major joint transitions are structurally readable without becoming dots, bands or final clothing detail.",
            "Limb chains, hand/foot blocks and attachments remain consistent from whole view and local crops.",
            "A fresh residual-mismatch sweep finds no major connection-level mismatch or upstream mass error.",
        ),
        suggested_crops=("shoulder+elbow", "pelvis+knee", "ankle+foot", "prop/strap attachment"),
    ),
    StageSpec(
        "P5_clean_blockin", 5, "Clean Block-in",
        "State a readable silhouette from verified structure while keeping construction subordinate.",
        ("whole silhouette","head/body proportion","torso-pelvis relation","stance","negative space","prop alignment","line hierarchy"),
        ("decisive outer contour","major internal breaks","major attached-object subpart topology","explicit silhouette-owner handoffs","overlap contours","only necessary surviving construction"),
        ("tone rendering","micro-detail","accidental contour welding between independent masses","beautification that hides structural error","cleaning a wrong structure instead of reopening it"),
        review_questions=(
            "Does the final block-in preserve the verified P1-P4 structure?",
            "Is the main silhouette readable without construction noise?",
            "Are head/body/leg/prop proportions credible against the subject?",
            "Has rejected construction receded through replayable retirement rather than accumulating as dead lines?",
            "At hair/garment/limb/attached-object handoffs, does each visible contour keep one semantic owner instead of visually welding two masses together?",
            "If a large attached object changes the silhouette, are its major width changes/subparts readable without micro-detail?",
        ),
        advance_when=(
            "The figure and attached objects are immediately readable from silhouette and major internal breaks.",
            "Construction is subordinate and no major structural error is being hidden by cleanup.",
            "No major block-in mismatch remains, and P5 did not draw outside P3/P4 merely to hide an upstream error.",
        ),
        suggested_crops=("whole silhouette", "head+torso", "pelvis+legs", "prop integration"),
    ),
)
