from .contract import StageContract, StageContractRegistry


FULL_BODY_CROQUIS_CONTRACTS = StageContractRegistry((
    StageContract(
        contract_id="full_body_croquis.P1.v1",
        stage_id="P1_gesture",
        tier=1,
        representation_name="gesture_and_weight_path",
        owns=(
            "craniofacial centre gesture",
            "whole-body line of action",
            "pelvis weight transfer",
            "support vs counterbalance role",
            "major attached-object axis when silhouette/balance requires it",
        ),
        inherits_from=None,
        must_preserve=(
            "subject-derived head direction",
            "subject-derived support side",
            "whole-body energy",
        ),
        allowed_representation=(
            "dominant crown→face→neck→spine→pelvis→support gesture",
            "open head-envelope arcs, including segmented crown/temporal/jaw arcs",
            "shoulder rhythm",
            "pelvis rhythm",
            "counterbalance-leg flow",
            "major attached-object axis",
            "minimal landing/ground cue",
        ),
        forbidden_representation=(
            "anatomical joint construction",
            "ribcage/pelvis mass contour",
            "full limb thickness",
            "clothing contour",
            "facial features",
            "rendered shading",
        ),
        detail_ceiling=(
            "global gesture",
            "face-direction cue",
            "weight relationship",
            "major prop direction only",
        ),
        next_stage_unlocks=(
            "head cross-axis",
            "shoulder axis",
            "pelvis axis",
            "major limb axes",
            "attached-object extent/breadth axis",
        ),
    ),
    StageContract(
        contract_id="full_body_croquis.P2.v1",
        stage_id="P2_primary_axes",
        tier=2,
        representation_name="primary_axes",
        owns=(
            "head cross-axis",
            "shoulder axis",
            "pelvis axis",
            "major arm direction chains",
            "major leg direction chains",
            "attached-object extent/breadth axis",
        ),
        inherits_from="P1_gesture",
        must_preserve=(
            "P1 crown-to-support gesture",
            "P1 face direction",
            "P1 support/counterbalance roles",
            "P1 weight landing",
        ),
        allowed_representation=(
            "dominant crown→face→neck→spine→pelvis→support gesture",
            "open head-envelope arcs",
            "shoulder rhythm",
            "pelvis rhythm",
            "counterbalance-leg flow",
            "major attached-object axis",
            "minimal landing/ground cue",
            "head cross-axis",
            "shoulder axis",
            "pelvis axis",
            "major limb axes",
            "attached-object extent/breadth axis",
        ),
        forbidden_representation=(
            "ribcage side contour",
            "ribcage mass contour",
            "pelvis side contour",
            "pelvis mass contour",
            "full arm thickness",
            "full thigh/shin thickness",
            "constructed hand block",
            "constructed foot/boot block",
            "joint anatomy",
            "clothing block-in",
            "final silhouette",
            "rendered shading",
        ),
        detail_ceiling=(
            "axis relationships",
            "tilt and twist direction",
            "foreshortening direction",
            "prop extent/breadth",
            "no volume closure",
        ),
        next_stage_unlocks=(
            "head/hair mass",
            "ribcage mass contour",
            "pelvis mass contour",
            "torso bridge",
            "tapered limb masses",
            "attached-object mass",
        ),
    ),
    StageContract(
        contract_id="full_body_croquis.P3.v1",
        stage_id="P3_primary_masses",
        tier=3,
        representation_name="connected_primary_masses",
        owns=(
            "head/hair mass",
            "ribcage mass",
            "pelvis mass",
            "torso bridge",
            "tapered limb masses",
            "attached-object mass",
            "major negative spaces",
        ),
        inherits_from="P2_primary_axes",
        must_preserve=(
            "P1 gesture and weight path",
            "P2 head/shoulder/pelvis axes",
            "P2 limb directions",
            "P2 attached-object axes",
        ),
        allowed_representation=(
            "dominant crown→face→neck→spine→pelvis→support gesture",
            "head cross-axis",
            "shoulder axis",
            "pelvis axis",
            "major limb axes",
            "attached-object extent/breadth axis",
            "head/hair mass",
            "ribcage mass contour",
            "pelvis mass contour",
            "torso bridge",
            "tapered limb masses",
            "attached-object mass",
        ),
        forbidden_representation=(
            "detailed shoulder insertion",
            "elbow joint plane construction",
            "knee joint plane construction",
            "ankle articulation",
            "hand/finger detail",
            "boot detail",
            "clothing folds",
            "final cleaned silhouette",
            "rendered shading",
        ),
        detail_ceiling=(
            "organic connected volumes",
            "limb taper",
            "major overlap",
            "major negative space",
            "no articulated joint detail",
        ),
        next_stage_unlocks=(
            "shoulder insertion",
            "elbow transition",
            "wrist transition",
            "hip-to-thigh insertion",
            "knee transition",
            "ankle-to-foot transition",
            "hand/foot block",
            "strap/holster/prop attachment",
        ),
    ),
    StageContract(
        contract_id="full_body_croquis.P4.v1",
        stage_id="P4_structural_connections",
        tier=4,
        representation_name="mannequin_connections",
        owns=(
            "shoulder insertion",
            "elbow/wrist transitions",
            "hip-to-thigh insertion",
            "knee/ankle transitions",
            "hand/foot blocks",
            "prop/strap/holster attachment and overlap",
        ),
        inherits_from="P3_primary_masses",
        must_preserve=(
            "P1 gesture and weight",
            "P2 axes",
            "P3 connected masses",
            "P3 negative spaces",
        ),
        allowed_representation=(
            "head/hair mass",
            "ribcage mass contour",
            "pelvis mass contour",
            "torso bridge",
            "tapered limb masses",
            "attached-object mass",
            "shoulder insertion",
            "elbow transition",
            "wrist transition",
            "hip-to-thigh insertion",
            "knee transition",
            "ankle-to-foot transition",
            "hand/foot block",
            "strap/holster/prop attachment",
        ),
        forbidden_representation=(
            "final polished clothing silhouette",
            "micro clothing folds",
            "surface texture",
            "tonal rendering",
            "micro facial detail",
        ),
        detail_ceiling=(
            "functional mannequin articulation",
            "attachment/overlap",
            "simple hands/feet",
            "no polish rendering",
        ),
        next_stage_unlocks=(
            "decisive outer contour",
            "major clothing silhouette",
            "major internal contour breaks",
            "construction-line retirement",
        ),
    ),
    StageContract(
        contract_id="full_body_croquis.P5.v1",
        stage_id="P5_clean_blockin",
        tier=5,
        representation_name="clean_blockin_contour",
        owns=(
            "decisive outer silhouette",
            "major clothing silhouette",
            "major internal contour breaks",
            "construction-line retirement",
            "silhouette-owner handoff",
            "clean attached-object silhouette",
        ),
        inherits_from="P4_structural_connections",
        must_preserve=(
            "P1 gesture and weight",
            "P2 directional axes",
            "P3 masses/negative spaces",
            "P4 joint/attachment logic",
        ),
        allowed_representation=(
            "head/hair mass",
            "major clothing silhouette",
            "decisive outer contour",
            "major internal contour breaks",
            "overlap contour between adjacent masses",
            "silhouette-owner handoff with a visible break or occlusion",
            "joint/attachment-informed contour",
            "hand/foot silhouette",
            "clean attached-object silhouette",
            "construction-line retirement",
        ),
        forbidden_representation=(
            "rendered tonal shading",
            "micro texture",
            "micro clothing folds",
            "accidental contour welding between independent semantic masses",
            "beautification that changes verified structure",
        ),
        detail_ceiling=(
            "clean block-in",
            "readable silhouette",
            "major internal structure only",
            "no tonal finish",
        ),
        next_stage_unlocks=(),
    ),
))
