from .contract import StageContract, StageContractRegistry


# v2 contracts. Each stage settles one class of information: pose, then skeletal
# direction, then volume, then real-form connection, then the surviving line.
# A stage is not "more lines than the last one"; it is a different question answered.
FULL_BODY_CROQUIS_CONTRACTS = StageContractRegistry((
    StageContract(
        contract_id="full_body_croquis.P1.v3",
        stage_id="P1_gesture",
        tier=1,
        representation_name="gesture_and_construction_centrelines",
        owns=(
            "head ovoid with facial centreline and eye-line cross",
            "face direction and head tilt",
            "spine centreline as an S-curve from the back of the neck",
            "pelvis centreline and its tilt",
            "shoulder line and its tilt",
            "line of action, distinct from the spine",
            "joint positions: shoulder, elbow, wrist, hip, knee, ankle",
            "arm and leg flow lines, including occluded segments",
            "loose torso mass",
            "foot direction and ground contact",
            "overall silhouette envelope",
            "major attached-object axis",
        ),
        inherits_from=None,
        must_preserve=(
            "subject-derived standing direction",
            "subject-derived weight side",
            "whole-body energy",
        ),
        allowed_representation=(
            "head ovoid with a curved facial centreline that passes crown -> nose -> chin",
            "an eye-line cross stating head tilt",
            "spine centreline starting behind the neck and running as an S-curve through mid-back, waist and sacrum",
            "pelvis centreline stating its tilt",
            "shoulder line stating its tilt",
            "one line of action that enters above the head, cuts across the body and lands ahead of the weight-bearing foot",
            "joint markers as small circles",
            "flowing limb lines from shoulder to wrist and from hip to ankle",
            "an inferred flow line through an occluded limb, ending where the hidden hand or foot must be",
            "a loose flowing torso mass",
            "a simple foot oval linked to the ankle, stating which way the foot points",
            "ground contact marks under the feet",
            "major attached-object axis",
        ),
        forbidden_representation=(
            "facial features other than the centreline and eye-line",
            "the hair silhouette used as the cranial outline",
            "the facial centreline collapsed into a plain vertical centre line",
            "face and spine centrelines merged into one stroke",
            "straight landmark-to-landmark joins that flatten limb curvature",
            "omitting an occluded limb because it is not visible",
            "hair",
            "garment structure",
            "footwear detail beyond a direction oval",
            "muscle definition",
            "cross-contours or closed volume",
            "attached-object detail",
            "rendered shading",
        ),
        detail_ceiling=(
            "a whole-body pose hypothesis at minimum information",
            "the centrelines that carry direction: face, spine, pelvis",
            "accurate joint centres and observed limb curvature",
            "loose mass, never resolved volume",
        ),
        next_stage_unlocks=(
            "limb segments as measured straight or lightly cylindrical axes",
            "ribcage and pelvis axis volumes",
            "simple hand and foot placement blocks",
            "attached-object length and tilt measured against the body",
        ),
    ),
    StageContract(
        contract_id="full_body_croquis.P2.v3",
        stage_id="P2_primary_axes",
        tier=2,
        representation_name="skeletal_axes_and_measured_segments",
        owns=(
            "upper-arm and forearm axes with measured length",
            "thigh and shin axes with measured length",
            "foreshortening of each segment",
            "neck axis",
            "ribcage centre axis and its volume box",
            "pelvis axis and its volume box",
            "hand and foot placement blocks",
            "attached-object length and tilt relative to the body",
        ),
        inherits_from="P1_gesture",
        must_preserve=(
            "P1 line of action",
            "P1 face, spine and pelvis centrelines",
            "P1 joint positions",
            "P1 ground contact and silhouette envelope",
        ),
        allowed_representation=(
            "limb segments as measured straight or lightly cylindrical axes",
            "ribcage and pelvis axis volumes",
            "the hip -> knee -> ankle -> foot chain stated as connected segments",
            "the shoulder -> elbow -> wrist -> hand chain stated as connected segments",
            "simple hand and foot placement blocks",
            "corrected joint positions when P1 flow proves a joint is misplaced",
            "attached-object length and tilt measured against the body",
        ),
        forbidden_representation=(
            "facial features",
            "hair",
            "clothing",
            "finished limb contour",
            "surface or garment detail",
            "rendered shading",
        ),
        detail_ceiling=(
            "segment length and foreshortening",
            "the skeleton as a measurable mannequin",
            "prop length and tilt relative to the body",
            "no finished volume",
        ),
        next_stage_unlocks=(
            "simple three-dimensional volumes wrapped around the P2 axes",
            "limb taper",
            "torso thickness and ribcage/pelvis rotation",
            "overlap and perspective cues",
        ),
    ),
    StageContract(
        contract_id="full_body_croquis.P3.v2",
        stage_id="P3_primary_masses",
        tier=3,
        representation_name="three_dimensional_masses",
        owns=(
            "head volume",
            "ribcage volume",
            "pelvis volume",
            "shoulder volume",
            "upper-arm and forearm volumes",
            "thigh and calf volumes",
            "simple hand and foot volumes",
            "ribcage and pelvis rotation",
            "front/back relationships and overlap",
            "whole-figure proportion",
            "attached-object volume",
        ),
        inherits_from="P2_primary_axes",
        must_preserve=(
            "P1 line of action and balance",
            "P1 face, spine and pelvis centrelines",
            "P2 segment lengths and foreshortening",
        ),
        allowed_representation=(
            "simple three-dimensional volumes wrapped around the P2 axes",
            "cross-contours that state the direction a volume points",
            "limb taper",
            "torso thickness and ribcage/pelvis rotation",
            "overlap and perspective cues",
            "a few garment or gear marks where they change the occupied volume",
        ),
        forbidden_representation=(
            "facial features",
            "individual hair strands",
            "clothing folds and seams",
            "finished garment silhouette",
            "hand and foot detail",
            "rendered shading",
        ),
        detail_ceiling=(
            "what volume the body occupies",
            "limb thickness and taper",
            "rotation, overlap and perspective",
            "no real-form surface yet",
        ),
        next_stage_unlocks=(
            "hair as a large mass over the cranium, not strand by strand",
            "how a garment hangs on the underlying volume",
            "major prop structure: barrel direction, stock, receiver, magazine, sling",
            "resolved hand, foot and footwear form",
        ),
    ),
    StageContract(
        contract_id="full_body_croquis.P4.v2",
        stage_id="P4_structural_connections",
        tier=4,
        representation_name="real_form_connection",
        owns=(
            "hair mass seated on the skull",
            "garment structure over the body (shoulder → sleeve → elbow → wrist)",
            "waistline and garment openings",
            "hand and foot form",
            "footwear structure",
            "attached-object major structure and its contact with the body",
            "strap, sling, holster and pocket attachment",
        ),
        inherits_from="P3_primary_masses",
        must_preserve=(
            "P3 volumes and proportion",
            "P2 joint positions",
            "P1 balance and ground contact",
        ),
        allowed_representation=(
            "how a garment hangs on the underlying volume",
            "hair as a large mass over the cranium, not strand by strand",
            "major prop structure: barrel direction, stock, receiver, magazine, sling",
            "contact and overlap points between object and body",
            "placement of facial features, kept minimal",
            "resolved hand, foot and footwear form",
        ),
        forbidden_representation=(
            "buttons, stitching and micro garment detail",
            "individual hair strands",
            "micro folds",
            "surface texture",
            "tonal rendering",
        ),
        detail_ceiling=(
            "how the real form connects to the body",
            "large structure of clothing, hair and equipment",
            "structure before decoration",
            "no rendering",
        ),
        next_stage_unlocks=(
            "selecting which explored line is the final form",
            "subordinating superseded construction rather than erasing history",
            "explicit occlusion handoff where one mass passes behind another",
        ),
    ),
    StageContract(
        contract_id="full_body_croquis.P5.v2",
        stage_id="P5_clean_blockin",
        tier=5,
        representation_name="clean_block_in",
        owns=(
            "decisive outer silhouette",
            "resolved face form",
            "resolved hair silhouette",
            "decided garment contour",
            "tidied hands and footwear",
            "settled equipment form",
            "construction-line retirement",
            "silhouette-owner handoff between overlapping masses",
        ),
        inherits_from="P4_structural_connections",
        must_preserve=(
            "P4 real-form structure",
            "P3 volume and proportion",
            "P1 balance and ground contact",
        ),
        allowed_representation=(
            "selecting which explored line is the final form",
            "subordinating superseded construction rather than erasing history",
            "resolved face and hair silhouette",
            "major internal contour breaks",
            "explicit occlusion handoff where one mass passes behind another",
        ),
        forbidden_representation=(
            "tonal shading and filled black areas",
            "surface texture",
            "excessive garment folds",
            "fine skin rendering",
            "accidental contour welding between independent masses",
            "beautification that changes verified structure",
        ),
        detail_ceiling=(
            "which lines survive",
            "readable silhouette and tidy internal line",
            "an under-drawing solid enough that detail will not collapse it",
            "no tonal finish",
        ),
        next_stage_unlocks=(),
    ),
))
